name: Daily Cron Job

on:
  workflow_dispatch:
    inputs:
      filter_text:
        description: 'Filter Text'
        required: true
  schedule:
    - cron: '0 10 * * *'  # Runs every day at 10:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt

    - name: Run Scraping
      env:
        USERNAME: ${{ secrets.KIT_USERNAME }}
        PASSWORD: ${{ secrets.KIT_PASSWORD }}
      run: |
        python ./src/main.py \
          --url "https://portal.wiwi.kit.edu/ys" \
          --faculty "KIT-Fakultät für Wirtschaftswissenschaften" \
          --filter-text "${{ github.event_name == 'schedule' && 'Zöllner' || inputs.filter_text }}"